### ISSUE TITLE
Lock filters not saving per page option.

### ISSUE THREAD

**Issue by andrius-urb** [optimistdigital/nova-detached-filters#10]
When i lock filters (green lock), my choosen per page option doesnt save and sets back to default one.

**Comment by KasparRosin** [comment]
This was an issue with [laravel/nova](https://github.com/laravel/nova). They have since merged my [pull request](https://github.com/laravel/nova/pull/1036) and released [3.15.0](https://nova.laravel.com/releases/3.15.0) that includes a fix for this. There isn't sadly anything i can do to make this work for earlier versions of nova. 
I will update the docs to reflect that this feature only works since version 3.15.0 of nova.
