### ISSUE TITLE
Multiple cards doesn't work

### ISSUE THREAD

**Issue by asivaneswaran** [optimistdigital/nova-detached-filters#11]
Hi,

If I have this following code:

```    
/**
     * Get the cards available for the request.
     *
     * @param  Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        /** @var NovaRequest $request */

        return [
            new NovaDetachedFilters($this->filters($request)),
            TeamCards::valid($request->findModelOrFail())->width('1/3')->onlyOnDetail(),
            TeamCards::rosterChange($request->findModelOrFail())->width('1/3')->onlyOnDetail(),
            TeamCards::payment($request->findModelOrFail())->width('1/3')->onlyOnDetail(),
        ];
    } 
```

The filters are not detached. But when I remove the 3 cards for my detail page, it works fine... Is that normal?

**Comment by KasparRosin** [comment]
That is not the expected behaviour. I tested it with cards/metrics and everything worked as expected for me. 
Can you verify that `https://{your-url}/nova-api/{your-resource}/cards` returns with all 4 card. Also please include the version of `optimistdigital/nova-detached-filters` you are using in your project that can help us debug your issue.
 
On a separate note: 
Since you are using $this->filters() for your NovaDetachedFilters, the filters can never be detached from the nova filter dropdown and they will also be shown in the nova filter dropdown menu. 

```
    use HasDetachedFilters; // Needs to have this trait

    public function cards()
    {
        return [
            new NovaDetachedFilters([
                new SelectFilter, // Showed only on card
                new SelectFilter2, // Showed both in dropdown menu and on card
            ]),
        ];
    }

    public function filters()
    {
        return [
            new SelectFilter2, // Showed both in dropdown menu and on card
            new SelectFilter3 // Shown only in dropdown menu
        ];
    }
```

From this example, you can see that `SelectFilter` is defined only in `NovaDetachedFilters` array which means that filter will not be shown in the nova dropdown menu.

**Comment by asivaneswaran** [comment]
It returns a 404. Would it be because my other cards are supposed to be `onlyOnDetail()` ?

**Comment by asivaneswaran** [comment]
It's my code that was faulty. Sorry about this.
